/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  IsDate,
  ValidateNested,
} from "class-validator";
import { Type } from "class-transformer";
import { AttendanceUpdateManyWithoutStudentsInput } from "./AttendanceUpdateManyWithoutStudentsInput";
import { RegisterUpdateManyWithoutStudentsInput } from "./RegisterUpdateManyWithoutStudentsInput";
import { EnrollmentUpdateManyWithoutStudentsInput } from "./EnrollmentUpdateManyWithoutStudentsInput";

@InputType()
class StudentUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  dateOfBirth?: Date | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: () => AttendanceUpdateManyWithoutStudentsInput,
  })
  @ValidateNested()
  @Type(() => AttendanceUpdateManyWithoutStudentsInput)
  @IsOptional()
  @Field(() => AttendanceUpdateManyWithoutStudentsInput, {
    nullable: true,
  })
  attendances?: AttendanceUpdateManyWithoutStudentsInput;

  @ApiProperty({
    required: false,
    type: () => RegisterUpdateManyWithoutStudentsInput,
  })
  @ValidateNested()
  @Type(() => RegisterUpdateManyWithoutStudentsInput)
  @IsOptional()
  @Field(() => RegisterUpdateManyWithoutStudentsInput, {
    nullable: true,
  })
  registers?: RegisterUpdateManyWithoutStudentsInput;

  @ApiProperty({
    required: false,
    type: () => EnrollmentUpdateManyWithoutStudentsInput,
  })
  @ValidateNested()
  @Type(() => EnrollmentUpdateManyWithoutStudentsInput)
  @IsOptional()
  @Field(() => EnrollmentUpdateManyWithoutStudentsInput, {
    nullable: true,
  })
  enrollments?: EnrollmentUpdateManyWithoutStudentsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  parent?: string | null;
}

export { StudentUpdateInput as StudentUpdateInput };
