/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
} from "class-validator";
import { ClassModelUpdateManyWithoutCoursesInput } from "./ClassModelUpdateManyWithoutCoursesInput";
import { Type } from "class-transformer";
import { EnrollmentUpdateManyWithoutCoursesInput } from "./EnrollmentUpdateManyWithoutCoursesInput";
import { AttendanceUpdateManyWithoutCoursesInput } from "./AttendanceUpdateManyWithoutCoursesInput";
import { RegisterUpdateManyWithoutCoursesInput } from "./RegisterUpdateManyWithoutCoursesInput";

@InputType()
class CourseUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  courseName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  courseCode?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: () => ClassModelUpdateManyWithoutCoursesInput,
  })
  @ValidateNested()
  @Type(() => ClassModelUpdateManyWithoutCoursesInput)
  @IsOptional()
  @Field(() => ClassModelUpdateManyWithoutCoursesInput, {
    nullable: true,
  })
  classes?: ClassModelUpdateManyWithoutCoursesInput;

  @ApiProperty({
    required: false,
    type: () => EnrollmentUpdateManyWithoutCoursesInput,
  })
  @ValidateNested()
  @Type(() => EnrollmentUpdateManyWithoutCoursesInput)
  @IsOptional()
  @Field(() => EnrollmentUpdateManyWithoutCoursesInput, {
    nullable: true,
  })
  enrollments?: EnrollmentUpdateManyWithoutCoursesInput;

  @ApiProperty({
    required: false,
    type: () => AttendanceUpdateManyWithoutCoursesInput,
  })
  @ValidateNested()
  @Type(() => AttendanceUpdateManyWithoutCoursesInput)
  @IsOptional()
  @Field(() => AttendanceUpdateManyWithoutCoursesInput, {
    nullable: true,
  })
  attendances?: AttendanceUpdateManyWithoutCoursesInput;

  @ApiProperty({
    required: false,
    type: () => RegisterUpdateManyWithoutCoursesInput,
  })
  @ValidateNested()
  @Type(() => RegisterUpdateManyWithoutCoursesInput)
  @IsOptional()
  @Field(() => RegisterUpdateManyWithoutCoursesInput, {
    nullable: true,
  })
  registers?: RegisterUpdateManyWithoutCoursesInput;
}

export { CourseUpdateInput as CourseUpdateInput };
