/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringFilter } from "../../util/StringFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { ClassModelListRelationFilter } from "../../classModel/base/ClassModelListRelationFilter";
import { EnrollmentListRelationFilter } from "../../enrollment/base/EnrollmentListRelationFilter";
import { AttendanceListRelationFilter } from "../../attendance/base/AttendanceListRelationFilter";
import { RegisterListRelationFilter } from "../../register/base/RegisterListRelationFilter";

@InputType()
class CourseWhereInput {
  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  courseName?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  courseCode?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  description?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => ClassModelListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ClassModelListRelationFilter)
  @IsOptional()
  @Field(() => ClassModelListRelationFilter, {
    nullable: true,
  })
  classes?: ClassModelListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => EnrollmentListRelationFilter,
  })
  @ValidateNested()
  @Type(() => EnrollmentListRelationFilter)
  @IsOptional()
  @Field(() => EnrollmentListRelationFilter, {
    nullable: true,
  })
  enrollments?: EnrollmentListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => AttendanceListRelationFilter,
  })
  @ValidateNested()
  @Type(() => AttendanceListRelationFilter)
  @IsOptional()
  @Field(() => AttendanceListRelationFilter, {
    nullable: true,
  })
  attendances?: AttendanceListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => RegisterListRelationFilter,
  })
  @ValidateNested()
  @Type(() => RegisterListRelationFilter)
  @IsOptional()
  @Field(() => RegisterListRelationFilter, {
    nullable: true,
  })
  registers?: RegisterListRelationFilter;
}

export { CourseWhereInput as CourseWhereInput };
