/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { RegisterService } from "../register.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { RegisterCreateInput } from "./RegisterCreateInput";
import { Register } from "./Register";
import { RegisterFindManyArgs } from "./RegisterFindManyArgs";
import { RegisterWhereUniqueInput } from "./RegisterWhereUniqueInput";
import { RegisterUpdateInput } from "./RegisterUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class RegisterControllerBase {
  constructor(
    protected readonly service: RegisterService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Register })
  @nestAccessControl.UseRoles({
    resource: "Register",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createRegister(
    @common.Body() data: RegisterCreateInput
  ): Promise<Register> {
    return await this.service.createRegister({
      data: {
        ...data,

        student: data.student
          ? {
              connect: data.student,
            }
          : undefined,

        course: data.course
          ? {
              connect: data.course,
            }
          : undefined,
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        registerDate: true,
        status: true,

        student: {
          select: {
            id: true,
          },
        },

        course: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Register] })
  @ApiNestedQuery(RegisterFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Register",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async registers(@common.Req() request: Request): Promise<Register[]> {
    const args = plainToClass(RegisterFindManyArgs, request.query);
    return this.service.registers({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        registerDate: true,
        status: true,

        student: {
          select: {
            id: true,
          },
        },

        course: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Register })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Register",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async register(
    @common.Param() params: RegisterWhereUniqueInput
  ): Promise<Register | null> {
    const result = await this.service.register({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        registerDate: true,
        status: true,

        student: {
          select: {
            id: true,
          },
        },

        course: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Register })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Register",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateRegister(
    @common.Param() params: RegisterWhereUniqueInput,
    @common.Body() data: RegisterUpdateInput
  ): Promise<Register | null> {
    try {
      return await this.service.updateRegister({
        where: params,
        data: {
          ...data,

          student: data.student
            ? {
                connect: data.student,
              }
            : undefined,

          course: data.course
            ? {
                connect: data.course,
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          registerDate: true,
          status: true,

          student: {
            select: {
              id: true,
            },
          },

          course: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Register })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Register",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteRegister(
    @common.Param() params: RegisterWhereUniqueInput
  ): Promise<Register | null> {
    try {
      return await this.service.deleteRegister({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          registerDate: true,
          status: true,

          student: {
            select: {
              id: true,
            },
          },

          course: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
