/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Register } from "./Register";
import { RegisterCountArgs } from "./RegisterCountArgs";
import { RegisterFindManyArgs } from "./RegisterFindManyArgs";
import { RegisterFindUniqueArgs } from "./RegisterFindUniqueArgs";
import { CreateRegisterArgs } from "./CreateRegisterArgs";
import { UpdateRegisterArgs } from "./UpdateRegisterArgs";
import { DeleteRegisterArgs } from "./DeleteRegisterArgs";
import { Student } from "../../student/base/Student";
import { Course } from "../../course/base/Course";
import { RegisterService } from "../register.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Register)
export class RegisterResolverBase {
  constructor(
    protected readonly service: RegisterService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Register",
    action: "read",
    possession: "any",
  })
  async _registersMeta(
    @graphql.Args() args: RegisterCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Register])
  @nestAccessControl.UseRoles({
    resource: "Register",
    action: "read",
    possession: "any",
  })
  async registers(
    @graphql.Args() args: RegisterFindManyArgs
  ): Promise<Register[]> {
    return this.service.registers(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Register, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Register",
    action: "read",
    possession: "own",
  })
  async register(
    @graphql.Args() args: RegisterFindUniqueArgs
  ): Promise<Register | null> {
    const result = await this.service.register(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Register)
  @nestAccessControl.UseRoles({
    resource: "Register",
    action: "create",
    possession: "any",
  })
  async createRegister(
    @graphql.Args() args: CreateRegisterArgs
  ): Promise<Register> {
    return await this.service.createRegister({
      ...args,
      data: {
        ...args.data,

        student: args.data.student
          ? {
              connect: args.data.student,
            }
          : undefined,

        course: args.data.course
          ? {
              connect: args.data.course,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Register)
  @nestAccessControl.UseRoles({
    resource: "Register",
    action: "update",
    possession: "any",
  })
  async updateRegister(
    @graphql.Args() args: UpdateRegisterArgs
  ): Promise<Register | null> {
    try {
      return await this.service.updateRegister({
        ...args,
        data: {
          ...args.data,

          student: args.data.student
            ? {
                connect: args.data.student,
              }
            : undefined,

          course: args.data.course
            ? {
                connect: args.data.course,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Register)
  @nestAccessControl.UseRoles({
    resource: "Register",
    action: "delete",
    possession: "any",
  })
  async deleteRegister(
    @graphql.Args() args: DeleteRegisterArgs
  ): Promise<Register | null> {
    try {
      return await this.service.deleteRegister(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Student, {
    nullable: true,
    name: "student",
  })
  @nestAccessControl.UseRoles({
    resource: "Student",
    action: "read",
    possession: "any",
  })
  async getStudent(
    @graphql.Parent() parent: Register
  ): Promise<Student | null> {
    const result = await this.service.getStudent(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Course, {
    nullable: true,
    name: "course",
  })
  @nestAccessControl.UseRoles({
    resource: "Course",
    action: "read",
    possession: "any",
  })
  async getCourse(@graphql.Parent() parent: Register): Promise<Course | null> {
    const result = await this.service.getCourse(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
